cnf:
    server:
        version: v1.7.5_17.01
server:
    port: 10010
db:
    postgres:
        url: jdbc:postgresql://tms_dbms:5432/isaver?charSet=UTF-8
        driver: org.postgresql.Driver
        name: isaveruser
        password: isaveruser
        validateQuery: select 1
        maxconnect: 10
        minconnect: 5
        wait: 3000
    mongo:
        host: tms_mongo
        port: 27017
        username: isaver
        password: dkdltpsxm
        database: isaver
mqtt:
    clientId: criticalAgent
    domain: tms_mqtt
    port: 1883
    username: icent
    password: dkdltpsxm
file:
    server:
        address: tms_file
        fileAttachedUploadPath: /upload/file/